-- MySQL Workbench Synchronization
-- Generated: 2024-05-24 22:48
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: heber

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuários` (
  `idUsuário` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL DEFAULT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `CPF` VARCHAR(11) NULL DEFAULT NULL,
  `sexo` VARCHAR(15) NULL DEFAULT NULL,
  `nomeMae` VARCHAR(45) NULL DEFAULT NULL,
  `telefoneCelular` VARCHAR(15) NULL DEFAULT NULL,
  `TelefoneFixo` VARCHAR(15) NULL DEFAULT NULL,
  `Cep` VARCHAR(45) NULL DEFAULT NULL,
  `Logradouro` VARCHAR(45) NULL DEFAULT NULL,
  `Bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `Estado` VARCHAR(45) NULL DEFAULT NULL,
  `NumeroResidencia` INT(11) NULL DEFAULT NULL,
  `Complemento` VARCHAR(45) NULL DEFAULT NULL,
  `Login` VARCHAR(45) NULL DEFAULT NULL,
  `Senha` VARCHAR(8) NULL DEFAULT NULL,
  `TipoUsuário` VARCHAR(2) NULL DEFAULT NULL,
  `statusDeUsuario` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuário`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Erros2FA` (
  `Usuarios_idUsuário` INT(11) NOT NULL,
  `Nome` VARCHAR(45) NULL DEFAULT NULL,
  `Pergunta` VARCHAR(45) NULL DEFAULT NULL,
  `repostaErrada` VARCHAR(45) NULL DEFAULT NULL,
  `respostaCerta` VARCHAR(45) NULL DEFAULT NULL,
  `Data` DATE NULL DEFAULT NULL,
  `Hora` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_Erros2FA_Usuário_idx` (`Usuarios_idUsuário` ASC),
  CONSTRAINT `fk_Erros2FA_Usuário`
    FOREIGN KEY (`Usuarios_idUsuário`)
    REFERENCES `mydb`.`usuários` (`idUsuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
insert mydb.usuários values(null,"MASTER","2000-11-09","14670545779","Masculino","Luciana","1234","1234","21725360","rua","bairro","cidade","estado","230","complemento","Master","1234","2");